name: warehouse
description: "Warehouse — gestor de catálogo de productos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^3.0.0
  get_it: ^9.3.0
  dio: ^5.11.1
  go_router: 17.5.0
  sizer: ^3.1.3
  hive_ce_flutter: ^2.4.0
  sentry_flutter: ^9.30.1
  sentry_dio: ^9.30.1
  intl: ^0.20.3
  slang: ^4.19.2
  slang_flutter: ^4.19.0
  package_info_plus: ^10.2.1
  shimmer: ^4.0.0
  bloc_concurrency: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0
  mocktail: ^1.0.5
  bloc_test: ^10.0.0
  fake_async: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/flags/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Variable.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Variable.ttf
