import 'package:flutter/material.dart';
import 'package:warehouse/core/theme/app_colors.dart';
import 'package:warehouse/core/theme/app_fonts.dart';

abstract final class AppTheme {
  static ThemeData get light => ThemeData(
    useMaterial3: true,
    brightness: Brightness.light,
    fontFamily: AppFont.outfit.family,
    scaffoldBackgroundColor: AppColors.light.bg,
    splashFactory: InkRipple.splashFactory,
    textSelectionTheme: TextSelectionThemeData(
      cursorColor: AppColors.light.accent,
      selectionColor: AppColors.light.accentSoft,
      selectionHandleColor: AppColors.light.accent,
    ),
    bottomSheetTheme: const BottomSheetThemeData(backgroundColor: Colors.transparent),
    extensions: const [AppColors.light],
    colorScheme: ColorScheme(
      brightness: Brightness.light,
      primary: AppColors.light.accent,
      onPrimary: AppColors.light.onAccent,
      primaryContainer: AppColors.light.accentSoft,
      onPrimaryContainer: AppColors.light.accent,
      secondary: AppColors.light.ink2,
      onSecondary: AppColors.light.surface,
      secondaryContainer: AppColors.light.surface2,
      onSecondaryContainer: AppColors.light.ink,
      tertiary: AppColors.light.ok,
      onTertiary: AppColors.light.surface,
      tertiaryContainer: AppColors.light.accentSoft,
      onTertiaryContainer: AppColors.light.ok,
      error: AppColors.light.bad,
      onError: AppColors.light.surface,
      errorContainer: AppColors.light.badSoft,
      onErrorContainer: AppColors.light.bad,
      surface: AppColors.light.surface,
      onSurface: AppColors.light.ink,
      onSurfaceVariant: AppColors.light.ink2,
      surfaceContainerHighest: AppColors.light.surface2,
      outline: AppColors.light.ink3,
      outlineVariant: AppColors.light.line,
      scrim: AppColors.light.scrim,
    ),
  );

  static ThemeData get dark => ThemeData(
    useMaterial3: true,
    brightness: Brightness.dark,
    fontFamily: AppFont.outfit.family,
    scaffoldBackgroundColor: AppColors.dark.bg,
    splashFactory: InkRipple.splashFactory,
    textSelectionTheme: TextSelectionThemeData(
      cursorColor: AppColors.dark.accent,
      selectionColor: AppColors.dark.accentSoft,
      selectionHandleColor: AppColors.dark.accent,
    ),
    bottomSheetTheme: const BottomSheetThemeData(backgroundColor: Colors.transparent),
    extensions: const [AppColors.dark],
    colorScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: AppColors.dark.accent,
      onPrimary: AppColors.dark.onAccent,
      primaryContainer: AppColors.dark.accentSoft,
      onPrimaryContainer: AppColors.dark.accent,
      secondary: AppColors.dark.ink2,
      onSecondary: AppColors.dark.surface,
      secondaryContainer: AppColors.dark.surface2,
      onSecondaryContainer: AppColors.dark.ink,
      tertiary: AppColors.dark.ok,
      onTertiary: AppColors.dark.surface,
      tertiaryContainer: AppColors.dark.accentSoft,
      onTertiaryContainer: AppColors.dark.ok,
      error: AppColors.dark.bad,
      onError: AppColors.dark.surface,
      errorContainer: AppColors.dark.badSoft,
      onErrorContainer: AppColors.dark.bad,
      surface: AppColors.dark.surface,
      onSurface: AppColors.dark.ink,
      onSurfaceVariant: AppColors.dark.ink2,
      surfaceContainerHighest: AppColors.dark.surface2,
      outline: AppColors.dark.ink3,
      outlineVariant: AppColors.dark.line,
      scrim: AppColors.dark.scrim,
    ),
  );
}
